import { Annotation } from "@langchain/langgraph";
import { FileOperation, ReviewResult } from "@letscode-dev-friendly/agents";
import { VerificationResult } from "@letscode-dev-friendly/validation";

interface EnhancedDiffResult {
    rawDiff: string;
    hasChanges: boolean;
    stats: {
        changedFilesCount: number;
        insertions: number;
        deletions: number;
    };
}

/**
 * The central structural memory graph(langgraph) for the agent execution lifecycle.
 */
const AgentState = Annotation.Root({
    ticketDescription: Annotation<string>(),
    repoPath: Annotation<string>(),
    repoSlug: Annotation<string>(),

    // Shared execution context gathered from the codebase retrieval layer
    retrievalContext: Annotation<any>(),

    // Captures the rich text architectural strategy document generated by the planner
    architecturePlan: Annotation<string>(),

    // The atomic DAG sequence map generated by the Decomposer
    operations: Annotation<FileOperation[]>({
        reducer: (x, y) => y ?? x,
    }),

    generationAttemptCount: Annotation<number>({
        reducer: (x, y) => x + y,
        default: () => 0
    }),
    maxAttempts: Annotation<number>(),

    lastVerificationResult: Annotation<VerificationResult | null>({
        reducer: (x, y) => y,
        default: () => null
    }),
    lastReviewResult: Annotation<ReviewResult | null>({
        reducer: (x, y) => y,
        default: () => null
    }),

    errors: Annotation<string[]>({
        reducer: (x, y) => x.concat(y),
        default: () => []
    }),
    isSuccessful: Annotation<boolean>({
        reducer: (x, y) => y,
        default: () => false
    })
});

// The TypeScript type from the LangGraph Annotation structure
type AgentStateType = typeof AgentState.State;

export {
    EnhancedDiffResult,
    AgentState,
    AgentStateType
}